-- SELECT * FROM [dbo].[DataSnapshots]
-- UPDATE [dbo].[DataSnapshots] SET SnapshotDate = DATEADD(YEAR, 1, SnapshotDate);
-- SELECT * FROM [dbo].[DataSnapshots] WHERE SnapshotDate = '2021-03-01 00:00:00.000'